export interface NseIndexItem {
  label: string;
  symbol: string; // URL-encoded symbol for NSE API
}

export interface NseIndexCategory {
  group: string;
  indices: NseIndexItem[];
}

export const NSE_INDEX_CATEGORIES: NseIndexCategory[] = [
  {
    group: 'Indices Eligible in Derivatives',
    indices: [
      { label: 'NIFTY 50', symbol: 'NIFTY 50' },
      { label: 'NIFTY BANK', symbol: 'NIFTY BANK' },
      { label: 'NIFTY FINANCIAL SERVICES', symbol: 'NIFTY FIN SERVICE' },
      { label: 'NIFTY INDIA FPI 150', symbol: 'NIFTY IND FPI 150' },
      { label: 'NIFTY MIDCAP SELECT', symbol: 'NIFTY MID SELECT' },
      { label: 'NIFTY NEXT 50', symbol: 'NIFTY NEXT 50' },
    ],
  },
  {
    group: 'Broad Market Indices',
    indices: [
      { label: 'NIFTY 100', symbol: 'NIFTY 100' },
      { label: 'NIFTY 200', symbol: 'NIFTY 200' },
      { label: 'NIFTY 500', symbol: 'NIFTY 500' },
      { label: 'NIFTY LARGEMIDCAP 250', symbol: 'NIFTY LARGEMID250' },
      { label: 'NIFTY MICROCAP 250', symbol: 'NIFTY MICROCAP250' },
      { label: 'NIFTY MIDCAP 100', symbol: 'NIFTY MIDCAP 100' },
      { label: 'NIFTY MIDCAP 150', symbol: 'NIFTY MIDCAP150' },
      { label: 'NIFTY MIDCAP 50', symbol: 'NIFTY MIDCAP 50' },
      { label: 'NIFTY MIDSMALLCAP400 50:50', symbol: 'NIFTY MIDSML400 5050' },
      { label: 'NIFTY MIDSMALLCAP 400', symbol: 'NIFTY MIDSML400' },
      { label: 'NIFTY SMALLCAP 500', symbol: 'NIFTY SMLCAP 500' },
      { label: 'NIFTY SMALLCAP 100', symbol: 'NIFTY SMLCAP 100' },
      { label: 'NIFTY SMALLCAP 250', symbol: 'NIFTY SMLCAP 250' },
      { label: 'NIFTY SMALLCAP 50', symbol: 'NIFTY SMLCAP 50' },
      { label: 'NIFTY TOTAL MARKET', symbol: 'NIFTY TOTAL MKT' },
      { label: 'NIFTY500 LARGEMIDSMALL EQUAL-CAP WEIGHTED', symbol: 'NIFTY500 LargMidSml EW' },
      { label: 'NIFTY500 MULTICAP 50:25:25', symbol: 'NIFTY500 MULTICAP' },
    ],
  },
  {
    group: 'Sectoral Market Indices',
    indices: [
      { label: 'NIFTY AUTO', symbol: 'NIFTY AUTO' },
      { label: 'NIFTY CEMENT', symbol: 'NIFTY CEMENT' },
      { label: 'NIFTY CHEMICALS', symbol: 'NIFTY CHEMICALS' },
      { label: 'NIFTY CONSUMER DURABLES', symbol: 'NIFTY CONSR DURBL' },
      { label: 'NIFTY FINANCIAL SERVICES EX-BANK', symbol: 'NIFTY FIN SERVICES EX-BNK' },
      { label: 'NIFTY FINANCIAL SERVICES 25/50', symbol: 'NIFTY FIN SER 2550' },
      { label: 'NIFTY FMCG', symbol: 'NIFTY FMCG' },
      { label: 'NIFTY HEALTHCARE INDEX', symbol: 'NIFTY HEALTHCARE' },
      { label: 'NIFTY IT', symbol: 'NIFTY IT' },
      { label: 'NIFTY MEDIA', symbol: 'NIFTY MEDIA' },
      { label: 'NIFTY METAL', symbol: 'NIFTY METAL' },
      { label: 'NIFTY MIDSMALL HEALTHCARE', symbol: 'NIFTY MIDSMALL HLTHCR' },
      { label: 'NIFTY MIDSMALL FINANCIAL SERVICES', symbol: 'NIFTY MIDSML FINSERV' },
      { label: 'NIFTY MIDSMALL IT & TELECOM', symbol: 'NIFTY MIDSML IT&TELE' },
      { label: 'NIFTY OIL & GAS', symbol: 'NIFTY OIL AND GAS' },
      { label: 'NIFTY PHARMA', symbol: 'NIFTY PHARMA' },
      { label: 'NIFTY PSU BANK', symbol: 'NIFTY PSU BANK' },
      { label: 'NIFTY PRIVATE BANK', symbol: 'NIFTY PVT BANK' },
      { label: 'NIFTY REALTY', symbol: 'NIFTY REALTY' },
      { label: 'NIFTY REITS & REALTY', symbol: 'NIFTY REITs&InvITs' },
      { label: 'NIFTY500 HEALTHCARE', symbol: 'NIFTY500 HLTHCR' },
    ],
  },
  {
    group: 'Thematic Market Indices',
    indices: [
      { label: 'NIFTY CAPITAL MARKETS', symbol: 'NIFTY CAPITAL MARKETS' },
      { label: 'NIFTY COMMODITIES', symbol: 'NIFTY COMMODITIES' },
      { label: 'NIFTY INDIA CONSUMPTION', symbol: 'NIFTY INDIA CONSUMPTION' },
      { label: 'NIFTY CORE HOUSING', symbol: 'NIFTY CORE HOUSING' },
      { label: 'NIFTY INDIA SELECT 5 CORPORATE GROUPS (MAATR)', symbol: 'NIFTY IND SEL 5 CORP GRP' },
      { label: 'NIFTY CPSE', symbol: 'NIFTY CPSE' },
      { label: 'NIFTY ENERGY', symbol: 'NIFTY ENERGY' },
      { label: 'NIFTY EV & NEW AGE AUTOMOTIVE', symbol: 'NIFTY EV & NEW AGE AUTOMOTIVE' },
      { label: 'NIFTY HOUSING', symbol: 'NIFTY HOUSING' },
      { label: 'NIFTY INDIA DEFENCE', symbol: 'NIFTY IND DEFENCE' },
      { label: 'NIFTY INDIA DIGITAL', symbol: 'NIFTY INDIA DIGITAL' },
      { label: 'NIFTY INDIA TOURISM', symbol: 'NIFTY INDIA TOURISM' },
      { label: 'NIFTY INDIA MANUFACTURING', symbol: 'NIFTY INDIA MANUFACTURING' },
      { label: 'NIFTY INFRASTRUCTURE', symbol: 'NIFTY INFRA' },
      { label: 'NIFTY INDIA INFRASTRUCTURE & LOGISTICS', symbol: 'NIFTY IND INFRA&LOGI' },
      { label: 'NIFTY INDIA INTERNET', symbol: 'NIFTY INDIA INTERNET' },
      { label: 'NIFTY IPO', symbol: 'NIFTY IPO' },
      { label: 'NIFTY MIDCAP LIQUID 15', symbol: 'NIFTY MIDCAP LIQ 15' },
      { label: 'NIFTY MNC', symbol: 'NIFTY MNC' },
      { label: 'NIFTY MOBILITY', symbol: 'NIFTY MOBILITY' },
      { label: 'NIFTY MIDSMALL INDIA CONSUMPTION', symbol: 'NIFTY MIDSML INDIA CONSUM' },
      { label: 'NIFTY500 MULTICAP INFRASTRUCTURE 50:30:20', symbol: 'NIFTY500 MCP INFRA 503020' },
      { label: 'NIFTY500 MULTICAP INDIA MANUFACTURING 50:30:20', symbol: 'NIFTY500 MC IND MFG 503020' },
      { label: 'NIFTY INDIA NEW AGE CONSUMPTION', symbol: 'NIFTY IND NEW AGE CONSUM' },
      { label: 'NIFTY NON-CYCLICAL CONSUMER', symbol: 'NIFTY NON-CYCLIC CONSR' },
      { label: 'NIFTY PSE', symbol: 'NIFTY PSE' },
      { label: 'NIFTY INDIA RAILWAYS PSU', symbol: 'NIFTY IND RAILWAYS PSU' },
      { label: 'NIFTY RURAL', symbol: 'NIFTY RURAL' },
      { label: 'NIFTY SERVICES SECTOR', symbol: 'NIFTY SERV SECTOR' },
      { label: 'NIFTY SHARIAH 25', symbol: 'NIFTY SHARIAH 25' },
      { label: 'NIFTY SME EMERGE', symbol: 'NIFTY SME EMERGE' },
      { label: 'NIFTY INDIA CORPORATE GROUP INDEX - TATA GROUP 25% CAP', symbol: 'NIFTY TATA GRP 25% CAP' },
      { label: 'NIFTY TRANSPORTATION & LOGISTICS', symbol: 'NIFTY TRANS & LOGISTIC' },
      { label: 'NIFTY WAVES', symbol: 'NIFTY WAVES' },
      { label: 'NIFTY100 ENHANCED ESG', symbol: 'NIFTY100 ENH ESG' },
      { label: 'NIFTY100 ESG', symbol: 'NIFTY100 ESG' },
      { label: 'NIFTY100 LIQUID 15', symbol: 'NIFTY100 LIQ 15' },
      { label: 'NIFTY50 SHARIAH', symbol: 'NIFTY50 SHARIAH' },
      { label: 'NIFTY500 SHARIAH', symbol: 'NIFTY500 SHARIAH' },
      { label: 'NIFTY CONGLOMERATE 50', symbol: 'NIFTY CONGLOMERATE 50' },
    ],
  },
  {
    group: 'Strategy Market Indices',
    indices: [
      { label: 'NIFTY ALPHA 50', symbol: 'NIFTY ALPHA 50' },
      { label: 'NIFTY ALPHA LOW-VOLATILITY 30', symbol: 'NIFTY ALPHALOWVOL 30' },
      { label: 'NIFTY ALPHA QUALITY LOW-VOLATILITY 30', symbol: 'NIFTY ALPHAQULOWVOL 30' },
      { label: 'NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30', symbol: 'NIFTY ALP QUA VAL LV 30' },
      { label: 'NIFTY DIVIDEND OPPORTUNITIES 50', symbol: 'NIFTY DIV OPPS 50' },
      { label: 'NIFTY GROWTH SECTORS 15', symbol: 'NIFTY GROWTH SECT 15' },
      { label: 'NIFTY HIGH BETA 50', symbol: 'NIFTY HIGH BETA 50' },
      { label: 'NIFTY LOW VOLATILITY 50', symbol: 'NIFTY LOW VOLATILITY 50' },
      { label: 'NIFTY MIDCAP150 QUALITY 50', symbol: 'NIFTY MIDCAP150 QLTY 50' },
      { label: 'NIFTY500 MULTICAP MOMENTUM QUALITY 50', symbol: 'NIFTY500 MC MOMQUL 50' },
      { label: 'NIFTY QUALITY LOW-VOLATILITY 30', symbol: 'NIFTY QUAL LV 30' },
      { label: 'NIFTY SMALLCAP250 QUALITY 50', symbol: 'NIFTY SMLCAP250 QLT 50' },
      { label: 'NIFTY TOTAL MARKET MOMENTUM QUALITY 50', symbol: 'NIFTY TOTMKT MOMQUL 50' },
      { label: 'NIFTY TOP 10 EQUAL WEIGHT', symbol: 'NIFTY TOP 10 EW' },
      { label: 'NIFTY TOP 15 EQUAL WEIGHT', symbol: 'NIFTY TOP 15 EW' },
      { label: 'NIFTY TOP 20 EQUAL WEIGHT', symbol: 'NIFTY TOP 20 EW' },
      { label: 'NIFTY100 ALPHA 30', symbol: 'NIFTY100 ALPHA 30' },
      { label: 'NIFTY100 EQUAL WEIGHT', symbol: 'NIFTY100 EQL WGT' },
      { label: 'NIFTY100 LOW VOLATILITY 30', symbol: 'NIFTY100 LOWVOL 30' },
      { label: 'NIFTY100 QUALITY 30', symbol: 'NIFTY100 QLTY 30' },
      { label: 'NIFTY200 ALPHA 30', symbol: 'NIFTY200 ALPHA 30' },
      { label: 'NIFTY200 QUALITY 30', symbol: 'NIFTY200 QLTY 30' },
      { label: 'NIFTY200 VALUE 30', symbol: 'NIFTY200 VALUE 30' },
      { label: 'NIFTY200 MOMENTUM 30', symbol: 'NIFTY200 MOMENTM 30' },
      { label: 'NIFTY50 EQUAL WEIGHT', symbol: 'NIFTY50 EQL WGT' },
      { label: 'NIFTY50 VALUE 20', symbol: 'NIFTY50 VALUE 20' },
      { label: 'NIFTY500 EQUAL WEIGHT', symbol: 'NIFTY500 EQL WGT' },
      { label: 'NIFTY500 FLEXICAP QUALITY 30', symbol: 'NIFTY500 FLXCAP QLT 30' },
      { label: 'NIFTY500 LOW VOLATILITY 50', symbol: 'NIFTY500 LOWVOL 50' },
      { label: 'NIFTY500 MULTIFACTOR MQVLV 50', symbol: 'NIFTY500 MULTIFACTOR 50' },
      { label: 'NIFTY500 QUALITY 50', symbol: 'NIFTY500 QLTY 50' },
      { label: 'NIFTY500 VALUE 50', symbol: 'NIFTY500 VALUE 50' },
      { label: 'NIFTY500 MOMENTUM 50', symbol: 'NIFTY500 MOMENTM 50' },
      { label: 'NIFTY MIDCAP150 MOMENTUM 50', symbol: 'NIFTY MIDCAP150 MOMENTM 50' },
      { label: 'NIFTY MIDSMALLCAP400 MOMENTUM QUALITY 100', symbol: 'NIFTY MIDSML400 MOMQUL 100' },
      { label: 'NIFTY SMALLCAP250 MOMENTUM QUALITY 100', symbol: 'NIFTY SMLCAP250 MOMQUL 100' },
    ],
  },
  {
    group: 'Others',
    indices: [
      { label: 'PERMITTED TO TRADE', symbol: 'PERMITTED TO TRADE' },
      { label: 'SECURITIES IN F&O', symbol: 'SECURITIES IN F&O' },
    ],
  },
];

// Flat list of all indices for quick lookup
export const ALL_NSE_INDICES: NseIndexItem[] = NSE_INDEX_CATEGORIES.flatMap(c => c.indices);

// Default selected index
export const DEFAULT_NSE_INDEX = ALL_NSE_INDICES.find(i => i.symbol === 'NIFTY 500') || NSE_INDEX_CATEGORIES[0].indices[0];
