import nodemailer from 'nodemailer';
import { prisma } from '../../database/db';

interface SendClientCredentialsOptions {
  email: string;
  name: string;
  userId: string;
  passwordHashOrPlain: string;
  loginUrl?: string;
}

export async function sendClientWelcomeEmail({
  email,
  name,
  userId,
  passwordHashOrPlain,
  loginUrl
}: SendClientCredentialsOptions) {
  const finalLoginUrl = loginUrl || 
    (typeof window !== 'undefined' ? `${window.location.origin}/vendor/login` : 
    (process.env.NEXT_PUBLIC_APP_URL ? `${process.env.NEXT_PUBLIC_APP_URL}/vendor/login` : 'http://localhost:3000/vendor/login'));
  try {
    // 1. Fetch settings from DB
    const dbSettings = await prisma.appSettings.findMany();
    const settings: Record<string, string> = {};
    dbSettings.forEach((s) => {
      settings[s.settingKey] = s.settingValue;
    });

    const emailStatus = settings['smtp_status'] === 'true' || settings['smtp_status'] === 'on';
    if (!emailStatus) {
      console.log('SMTP status is OFF. Mail sending skipped.');
      return { success: false, reason: 'SMTP_DISABLED' };
    }

    const host = settings['smtp_host'];
    const port = parseInt(settings['smtp_port'] || '587', 10);
    const user = settings['smtp_user'];
    const pass = settings['smtp_password'];
    const fromName = settings['smtp_sender_name'] || 'Growffiy';
    const encryption = settings['smtp_encryption'] || 'tls'; // tls, ssl, none

    if (!host || !user || !pass) {
      console.warn('SMTP Credentials are not configured properly in settings.');
      return { success: false, reason: 'SMTP_NOT_CONFIGURED' };
    }

    // 2. Create Nodemailer Transporter
    const secure = encryption === 'ssl' || port === 465;
    const transporter = nodemailer.createTransport({
      host,
      port,
      secure,
      auth: {
        user,
        pass,
      },
      tls: {
        rejectUnauthorized: false
      }
    });

    // 3. Compose Email HTML
    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; borderRadius: 12px; backgroundColor: #ffffff;">
        <div style="text-align: center; border-bottom: 1px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 20px;">
          <h2 style="color: #2563eb; margin: 0;">Welcome to ${fromName}!</h2>
        </div>
        
        <p style="font-size: 15px; color: #1e293b; line-height: 1.5;">Hello <strong>${name}</strong>,</p>
        <p style="font-size: 15px; color: #475569; line-height: 1.5;">Your client trading account has been successfully generated by the administrator. Use the credentials below to log in and manage your portfolio:</p>
        
        <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 18px; border-radius: 8px; margin: 20px 0;">
          <table style="width: 100%; font-size: 14px; border-collapse: collapse;">
            <tr>
              <td style="padding: 6px 0; color: #64748b; width: 120px; font-weight: 600;">Client Login ID:</td>
              <td style="padding: 6px 0; color: #0f172a; font-weight: 700; font-family: monospace;">${userId}</td>
            </tr>
            <tr>
              <td style="padding: 6px 0; color: #64748b; font-weight: 600;">Password:</td>
              <td style="padding: 6px 0; color: #0f172a; font-weight: 700; font-family: monospace;">${passwordHashOrPlain}</td>
            </tr>
            <tr>
              <td style="padding: 6px 0; color: #64748b; font-weight: 600;">Login URL:</td>
              <td style="padding: 6px 0;">
                <a href="${finalLoginUrl}" target="_blank" style="color: #2563eb; font-weight: 600; text-decoration: underline;">
                  ${finalLoginUrl}
                </a>
              </td>
            </tr>
          </table>
        </div>

        <p style="font-size: 14px; color: #ef4444; font-weight: 500; margin-top: 20px;">
          * For security reasons, we highly recommend changing your password after your first login.
        </p>

        <div style="margin-top: 30px; text-align: center;">
          <a href="${finalLoginUrl}" target="_blank" style="background-color: #2563eb; color: #ffffff; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: 600; font-size: 14px; display: inline-block;">
            Access Client Portal
          </a>
        </div>

        <div style="border-top: 1px solid #e2e8f0; margin-top: 30px; padding-top: 20px; text-align: center; color: #94a3b8; font-size: 12px;">
          This is an automated system email. Please do not reply directly.
        </div>
      </div>
    `;

    // 4. Send the mail
    const mailOptions = {
      from: `"${fromName}" <${user}>`,
      to: email,
      subject: `Your ${fromName} Client Credentials & Login details`,
      html: emailHtml,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('Welcome email successfully dispatched:', info.messageId);
    return { success: true, messageId: info.messageId };

  } catch (err: any) {
    console.error('Failed to send welcome email:', err);
    return { success: false, error: err.message };
  }
}

interface SendClientOtpOptions {
  email: string;
  name: string;
  otp: string;
}

export async function sendClientOtpEmail({
  email,
  name,
  otp
}: SendClientOtpOptions) {
  try {
    const dbSettings = await prisma.appSettings.findMany();
    const settings: Record<string, string> = {};
    dbSettings.forEach((s) => {
      settings[s.settingKey] = s.settingValue;
    });

    const emailStatus = settings['smtp_status'] === 'true' || settings['smtp_status'] === 'on';
    if (!emailStatus) {
      console.log('SMTP status is OFF. OTP mail skipped.');
      return { success: false, reason: 'SMTP_DISABLED' };
    }

    const host = settings['smtp_host'];
    const port = parseInt(settings['smtp_port'] || '587', 10);
    const user = settings['smtp_user'];
    const pass = settings['smtp_password'];
    const fromName = settings['smtp_sender_name'] || 'Growffiy';
    const encryption = settings['smtp_encryption'] || 'tls';

    if (!host || !user || !pass) {
      console.warn('SMTP Credentials are not configured.');
      return { success: false, reason: 'SMTP_NOT_CONFIGURED' };
    }

    const secure = encryption === 'ssl' || port === 465;
    const transporter = nodemailer.createTransport({
      host,
      port,
      secure,
      auth: { user, pass },
      tls: { rejectUnauthorized: false }
    });

    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="text-align: center; border-bottom: 1px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 20px;">
          <h2 style="color: #2563eb; margin: 0;">${fromName} Password Reset OTP</h2>
        </div>
        
        <p style="font-size: 15px; color: #1e293b; line-height: 1.5;">Hello <strong>${name}</strong>,</p>
        <p style="font-size: 15px; color: #475569; line-height: 1.5;">We received a request to reset your password. Use the following 6-digit verification code (OTP) to proceed. This code is valid for 10 minutes:</p>
        
        <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 20px; border-radius: 8px; margin: 20px 0; text-align: center;">
          <span style="font-size: 32px; font-weight: 800; letter-spacing: 6px; color: #2563eb; font-family: monospace; display: block; margin: 0 auto;">${otp}</span>
        </div>

        <p style="font-size: 14px; color: #ef4444; font-weight: 500; margin-top: 20px;">
          * If you did not request a password reset, please ignore this email or contact support.
        </p>

        <div style="border-top: 1px solid #e2e8f0; margin-top: 30px; padding-top: 20px; text-align: center; color: #94a3b8; font-size: 12px;">
          This is an automated system email. Please do not reply directly.
        </div>
      </div>
    `;

    const mailOptions = {
      from: `"${fromName}" <${user}>`,
      to: email,
      subject: `Password Reset Verification Code for ${fromName}`,
      html: emailHtml,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('OTP email successfully dispatched:', info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (err: any) {
    console.error('Failed to send OTP email:', err);
    return { success: false, error: err.message };
  }
}
